### ISSUE TITLE
Add robot home button in the Ui

### ISSUE THREAD

**Issue by rkojcev** [ros-industrial-attic/fermi#19]
Sometimes when we execute the robot we would like to return it in the initial state. I would like to add "go home" button to the UI which will execute a robot motion that returns the robot at its start state, as configured from MoveIt.

**Comment by rkojcev** [comment]
added this feature and updated the master branch. Once all the issues are closed I will make a pull request to the hydro-devel branch.

**Comment by gavanderhoorn** [comment]
@rkojcev: out of curiosity: how did you implement the 'go to home' button? Is there any convention that MoveIt config pkgs should follow for this to work (ie: what is actually the 'home position': all joints at `0`)?

**Comment by rkojcev** [comment]
@gavanderhoorn  in the current implementation the home position brings the robot to the same position as the one that robot is set to from the MoveIt configuration. This depends on how you defined the start position in the MoveIt setup assistant and equals to the one that the robot is first loaded once you call it with the roslaunch.

**Comment by gavanderhoorn** [comment]
> [..] the same position as the one that robot is set to from the MoveIt configuration. This depends on how you defined the start position in the MoveIt setup assistant [..]

Well that was exactly my question :): what do you consider the 'start position'?

Are you referring to the _Robot Poses_ screen of the Setup Assistant? The ROS-I [MoveIt tutorial](http://wiki.ros.org/Industrial/Tutorials/Create_a_MoveIt_Pkg_for_an_Industrial_Robot) does have a section on the poses (step 2.6), but it is marked optional. That's why I asked whether the MoveIt configs had to follow any conventions (ie: it should have a `pose` defined with a certain name).

PS: I'm lazy: if you could point me to the code, I'm sure I can figure it out :).

**Comment by rkojcev** [comment]
@gavanderhoorn the plugin doesn't require you to set up any additional poses in the MoveIt setup assistant. It uses the same principle which is used to set up the User Interaction Marker (red arrow) starting pose once you load the plugin.

You can check the implementation [here](https://github.com/ros-industrial-consortium/fermi/blob/hydro-devel/moveit_cartesian_plan_plugin/src/generate_cartesian_path.cpp#L152-177)

The relevant function that sets the robot "home" pose as well as the starting pose of the user interaction marker is the following:

```
 const Eigen::Affine3d &end_effector_state = kinematic_state->getGlobalLinkTransform(moveit_group_->getEndEffectorLink());
```

Hope this helps :)
