### ISSUE TITLE
cartesian path planner plugin kinetic support

### ISSUE THREAD

**Issue by gokul-narayanan1** [ros-industrial-attic/fermi#43]
Does this package support ros kinetic?I downloaded the package and when I compiled the package with catkin, there where lot of errors.

**Comment by smith-doug** [comment]
RViz uses Qt5 in Kinetic.  The plugin uses Qt4.  It also uses the move_group_interface namespace which was removed.

I hacked/slashed at the indigo-devel-impedance branch to get it to build/run in Kinetic.  I'm pretty new to Ros so I don't really know what kind of side effects it might have, but I'm able to create/run paths.  https://github.com/smith-doug/fermi/tree/kinetic-devel-impedance

**Comment by rkojcev** [comment]
@smith-doug is right. The plugin is not compatible with MoveIt kinetic release due to many changes they introduced in that version.

Since I do not have much time working on this at the moment it would be great if someone ports the plugin to kinetic version.
You are welcomed to make a pull request to this repository.

**Comment by tbs845** [comment]
@smith-doug is it necessary to install Qt 5 to run this plugin?

**Comment by minhson0307** [comment]
Hello, can you solve this problem? Please help me
