### ISSUE TITLE
Euler Angles Singularity

### ISSUE THREAD

**Issue by rkojcev** [ros-industrial-attic/fermi#6]
When converting Euler angles between  **_tf::Transform**_ and **_geometry_msgs::Pose**_ the singularity of Euler angles is handled differently. 

For example: an angle with 180 in **_tf::Transform**_ is converted as -180 in **_geometry_msgs::Pose**_.

Proposed solution: replace all tf::Transform with geometry_msgs::Pose
@shaun-edwards and @jrgnicho what is your opinion about this?

**Comment by jrgnicho** [comment]
I'm not sure that I follow your question, the geometry_msgs::Pose message does not have any fields for Euler angles, the rotation part of the pose is stored as a quaternion (x, y, z, w).  Normally, tf::Transform structures are used to perform linear algebra operations and the end result is then saved in a geometry_msgs::Pose so that it can be sent through a ros message.

**Comment by rkojcev** [comment]
This bug was solved by following @jrgnicho suggestions
